# force1

trigger:
- '*'

pool:
  vmImage: 'windows-latest'
  demands:
  - npm
  tags: DEV

stages:
- stage: DeploySITRC
  displayName: Deploy Release Candidate to SIT
  variables:
    MemCachedServiceName: 'spooler'
    BuildVersion: $[ stageDependencies.Pre_Build.Pre_Build.outputs['SetVersionNumber.NewBuildVersion'] ]
    RevisionVersion: $[ stageDependencies.Pre_Build.Pre_Build.outputs['SetVersionNumber.NewVersion'] ]
    buildConfiguration: 'Release'
    wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
    dotnetSdkVersion: '3.1.300'
    azuresub: "DevSecOps"
    environment: 'DEV'
    tags: 'DEV'

  jobs:
  - deployment:
    environment:
      name: 'DEV'
      resourceType: VirtualMachine
      tags: 'DEV'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:

          - task: PowerShell@2
            displayName: 'Stop Memcached Service'
            inputs:
              filePath: '$(Build.SourcesDirectory)\scripts\ManageServices.ps1'
              arguments: '-ServiceName $(MemCachedServiceName) -ServiceAction Stop'
              failOnStderr: true
        
          - task: PowerShell@2
            displayName: 'Agent Rights Check'
            inputs:
              filePath: '$(Build.SourcesDirectory)\scripts\PipelineAgentRightsCheck.ps1'   
              arguments: '-ServiceName $(MemCachedServiceName)'
              failOnStderr: true
